ln -s ../../src/mod_vm/ loris_framework/src/mod_vm
ln -s ../../src/mod_vm_arch loris_framework/src/mod_vm_arch
ln -s ../../src/mod_vm_arch_mips_cp0 loris_framework/src/mod_vm_arch_mips_cp0
ln -s ../../src/mod_vm_arch_mips_cpu loris_framework/src/mod_vm_arch_mips_cpu
ln -s ../../src/mod_vm_device loris_framework/src/mod_vm_device
ln -s ../../src/mod_vm_device_manager loris_framework/src/mod_vm_device_manager
ln -s ../../src/mod_vm_device_vtty loris_framework/src/mod_vm_device_vtty
ln -s ../../src/mod_vm_memory loris_framework/src/mod_vm_memory
ln -s ../../files/vmlinux loris_framework/files/vmlinux
